-- Test SQL Import
INSERT INTO businesses (
  location_id, slug, name, description,
  category, subcategory, image, photos, videos,
  phone, email, website,
  address_street, address_city, address_state, address_zip,
  latitude, longitude, hours,
  rating, review_count, price_range,
  specialties, amenities, tags,
  listing_tier, is_featured, backlink_enabled
) VALUES

  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'conejos-tex-mex-cantina', 'Conejos Tex-Mex Cantina', 'Conejos Tex-Mex Cantina is a mexican business located in Leander. Restaurant',
   'restaurants', 'Mexican restaurants',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAwep4gGPSfnXfFcc6FJkyMkj6-j9cSiCZnYVst8Xf_raT8jK9Y-_GJlLNRba9K4bKo0OoEhvGFvF-9RhPbI7U3_RO1A9X300Q79cIQ6gBkQfcbvHcIMB8d9Pk5at-T_-J_QciXQqkKLstNQc=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAwep4gGPSfnXfFcc6FJkyMkj6-j9cSiCZnYVst8Xf_raT8jK9Y-_GJlLNRba9K4bKo0OoEhvGFvF-9RhPbI7U3_RO1A9X300Q79cIQ6gBkQfcbvHcIMB8d9Pk5at-T_-J_QciXQqkKLstNQc=w800-h500-k-no'], '{}',
   '+1 512-548-5121', NULL, 'http://conejostx.com/',
   '2082 N US Hwy 183 Suite 150',
   'Leander', 'TX',
   '78641',
   30.6268298, -97.8656991,
   '{"monday":{"open":"11AM","close":"9PM","isOpen":true},"tuesday":{"open":"11AM","close":"9PM","isOpen":true},"wednesday":{"open":"11AM","close":"9PM","isOpen":true},"thursday":{"open":"11AM","close":"9PM","isOpen":true},"friday":{"open":"11AM","close":"10PM","isOpen":true},"saturday":{"open":"10AM","close":"10PM","isOpen":true},"sunday":{"open":"10AM","close":"9PM","isOpen":true}}',
   4.9, 1404,
   NULL,
   ARRAY['Restaurant'], '{}', ARRAY['restaurants', 'Mexican restaurants', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'jardin-del-rey', 'Jardin Del Rey', 'Jardin Del Rey is a mexican business located in Leander. Mexican restaurant',
   'restaurants', 'Mexican restaurants',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAwerOVQYdlGMKdAlRGk5PmSvKE1s_ZdLeYXw5y1_el6aevlQOSNZJjk-LLXZKPpgP2kIbGU43J_i2la3_pReHOSNdX9EEResxfv1JtU38W9wF-2nCksPdo_TJ13sqGnHAu7UDw4I=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAwerOVQYdlGMKdAlRGk5PmSvKE1s_ZdLeYXw5y1_el6aevlQOSNZJjk-LLXZKPpgP2kIbGU43J_i2la3_pReHOSNdX9EEResxfv1JtU38W9wF-2nCksPdo_TJ13sqGnHAu7UDw4I=w800-h500-k-no'], '{}',
   '+1 512-528-0203', NULL, 'https://www.jardindelreyleander.com/',
   '703 N US Hwy 183',
   'Leander', 'TX',
   '78641',
   30.569606099999998, -97.8496605,
   '{"monday":{"open":"11AM","close":"9PM","isOpen":true},"tuesday":{"open":"11AM","close":"9PM","isOpen":true},"wednesday":{"open":"11AM","close":"9PM","isOpen":true},"thursday":{"open":"11AM","close":"9PM","isOpen":true},"friday":{"open":"11AM","close":"10PM","isOpen":true},"saturday":{"open":"9AM","close":"10PM","isOpen":true},"sunday":{"open":"9AM","close":"9PM","isOpen":true}}',
   4.4, 2105,
   '$',
   ARRAY['Mexican restaurant'], '{}', ARRAY['restaurants', 'Mexican restaurants', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'la-tapatia-mexican-restaurant-and-bar', 'La Tapatia Mexican Restaurant and Bar', 'La Tapatia Mexican Restaurant and Bar is a mexican business located in Leander. Mexican restaurant, Restaurant',
   'restaurants', 'Mexican restaurants',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAwepKVyhApAB_zExvjhcFhK2ID3vV8VVNLkYe5VgRCFe1g5bSCIn_HlxfV5zj-go706qDgCvSHJ3pTTU6A-wVFRSISsPy-GWswsEZDwcHWBJGQo0e-erU2eoXmPQZbGGIb2S0-KxlMw=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAwepKVyhApAB_zExvjhcFhK2ID3vV8VVNLkYe5VgRCFe1g5bSCIn_HlxfV5zj-go706qDgCvSHJ3pTTU6A-wVFRSISsPy-GWswsEZDwcHWBJGQo0e-erU2eoXmPQZbGGIb2S0-KxlMw=w800-h500-k-no'], '{}',
   '+1 512-259-5019', NULL, 'https://www.latapatialeandertx.com/',
   '651 N US-183 Suite 310',
   'Leander', 'TX',
   '78641',
   30.583047999999998, -97.858363,
   '{"monday":{"open":"7AM","close":"10PM","isOpen":true},"tuesday":{"open":"7AM","close":"10PM","isOpen":true},"wednesday":{"open":"7AM","close":"10PM","isOpen":true},"thursday":{"open":"7AM","close":"10PM","isOpen":true},"friday":{"open":"7AM","close":"10PM","isOpen":true},"saturday":{"open":"7AM","close":"10PM","isOpen":true},"sunday":{"open":"7AM","close":"9PM","isOpen":true}}',
   4, 1513,
   '$',
   ARRAY['Mexican restaurant, Restaurant'], '{}', ARRAY['restaurants', 'Mexican restaurants', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'casamigos-mexican-grill', 'Casamigos Mexican Grill', 'Casamigos Mexican Grill is a mexican business located in Leander. Tex-Mex restaurant',
   'restaurants', 'Mexican restaurants',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAwermsidte5_QkML02A9BtGtuffrnu7SBnLFaY14YcxIzft2I2e2udJcjprqK5MNEjLlKdtRkzDLP-QKq57rP9w8Hhy4OptFl4vZyl6X64p4_6HUPlV5rXUZTFNbvemhm-TIUdBDK=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAwermsidte5_QkML02A9BtGtuffrnu7SBnLFaY14YcxIzft2I2e2udJcjprqK5MNEjLlKdtRkzDLP-QKq57rP9w8Hhy4OptFl4vZyl6X64p4_6HUPlV5rXUZTFNbvemhm-TIUdBDK=w800-h500-k-no'], '{}',
   '+1 512-456-7895', NULL, 'https://www.casamigosmexicangrill.com/',
   '15609 Ronald Reagan Blvd',
   'Leander', 'TX',
   '78641',
   30.564304999999997, -97.80181309999999,
   '{"monday":{"open":"11AM","close":"9PM","isOpen":true},"tuesday":{"open":"11AM","close":"9PM","isOpen":true},"wednesday":{"open":"11AM","close":"9PM","isOpen":true},"thursday":{"open":"11AM","close":"9PM","isOpen":true},"friday":{"open":"11AM","close":"9PM","isOpen":true},"saturday":{"open":"11AM","close":"9PM","isOpen":true},"sunday":{"open":"11AM","close":"9PM","isOpen":true}}',
   4.4, 420,
   '$',
   ARRAY['Tex-Mex restaurant'], '{}', ARRAY['restaurants', 'Mexican restaurants', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'blue-corn-harvest-bar-and-grill-leander', 'Blue Corn Harvest Bar and Grill Leander', 'Blue Corn Harvest Bar and Grill Leander is a mexican business located in Leander. Restaurant',
   'restaurants', 'Mexican restaurants',
   'https://lh3.googleusercontent.com/p/AF1QipO2-t_e27i1_xPYy6mIiI2NCLB5JqaBhjD0d4D3=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/p/AF1QipO2-t_e27i1_xPYy6mIiI2NCLB5JqaBhjD0d4D3=w800-h500-k-no'], '{}',
   '+1 512-337-7633', NULL, 'http://www.bluecornharvest.com/',
   '11840 Hero Way W Bldg A',
   'Leander', 'TX',
   '78641',
   30.5781723, -97.8689728,
   '{"monday":{"open":"11AM","close":"9PM","isOpen":true},"tuesday":{"open":"11AM","close":"9PM","isOpen":true},"wednesday":{"open":"11AM","close":"9PM","isOpen":true},"thursday":{"open":"11AM","close":"9PM","isOpen":true},"friday":{"open":"11AM","close":"10PM","isOpen":true},"saturday":{"open":"10AM","close":"10PM","isOpen":true},"sunday":{"open":"10AM","close":"9PM","isOpen":true}}',
   4.5, 923,
   '$$',
   ARRAY['Restaurant'], '{}', ARRAY['restaurants', 'Mexican restaurants', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'the-hive-salon-spa', 'The Hive Salon & Spa', 'The Hive Salon & Spa is a hair business located in Leander. Hair salon, Facial spa, Skin care clinic, Spa, Waxing hair removal service',
   'beauty', 'Hair salons',
   'https://lh3.googleusercontent.com/p/AF1QipP2rhMXMhtB-e1MDOvS7J_-b8kKIycLZ3BXJzMI=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/p/AF1QipP2rhMXMhtB-e1MDOvS7J_-b8kKIycLZ3BXJzMI=w800-h500-k-no'], '{}',
   '+1 737-314-1655', NULL, 'http://thehivesalonleander.com/',
   '11892 Hero Way W Suite f',
   'Leander', 'TX',
   '78641',
   30.5775252, -97.8705646,
   '{"monday":{"open":"","close":"","isOpen":false},"tuesday":{"open":"9AM","close":"6PM","isOpen":true},"wednesday":{"open":"9AM","close":"6PM","isOpen":true},"thursday":{"open":"9AM","close":"6PM","isOpen":true},"friday":{"open":"9AM","close":"6PM","isOpen":true},"saturday":{"open":"9AM","close":"4PM","isOpen":true},"sunday":{"open":"","close":"","isOpen":false}}',
   4.8, 189,
   NULL,
   ARRAY['Hair salon, Facial spa, Skin care clinic, Spa, Waxing hair removal service'], '{}', ARRAY['beauty', 'Hair salons', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'glow-grow-salon-and-boutique', 'Glow & Grow Salon and Boutique', 'Glow & Grow Salon and Boutique is a hair business located in Leander. Beauty salon',
   'beauty', 'Hair salons',
   'https://lh3.googleusercontent.com/p/AF1QipNVdgssv32Ug5QqDPn3UsjdcMPKo3sjMtgChJbq=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/p/AF1QipNVdgssv32Ug5QqDPn3UsjdcMPKo3sjMtgChJbq=w800-h500-k-no'], '{}',
   '+1 512-337-7028', NULL, 'https://glowandgrowtx.com/',
   '10824 E Crystal Falls Pkwy #505',
   'Leander', 'TX',
   '78641',
   30.565585, -97.8177711,
   '{"monday":{"open":"","close":"","isOpen":false},"tuesday":{"open":"9AM","close":"5PM","isOpen":true},"wednesday":{"open":"9AM","close":"5PM","isOpen":true},"thursday":{"open":"9AM","close":"5PM","isOpen":true},"friday":{"open":"9AM","close":"5PM","isOpen":true},"saturday":{"open":"9AM","close":"4PM","isOpen":true},"sunday":{"open":"","close":"","isOpen":false}}',
   4.9, 75,
   NULL,
   ARRAY['Beauty salon'], '{}', ARRAY['beauty', 'Hair salons', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'salt-and-waves-salon', 'Salt and Waves Salon', 'Salt and Waves Salon is a hair business located in Leander. Hair salon',
   'beauty', 'Hair salons',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAweraVhkE_HyNsJ5hdV03Rx4h2QgIuoShslxcUv2ugUIIArxkJsoeR6FlqdKzMQCzgEOzaTvA7EDTtQzgdljupjyGGTSiQPk-AdA0rqoyaC8Rsru5g9K4wkqKWD12LwSURGNvpnEcEA=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAweraVhkE_HyNsJ5hdV03Rx4h2QgIuoShslxcUv2ugUIIArxkJsoeR6FlqdKzMQCzgEOzaTvA7EDTtQzgdljupjyGGTSiQPk-AdA0rqoyaC8Rsru5g9K4wkqKWD12LwSURGNvpnEcEA=w800-h500-k-no'], '{}',
   '+1 512-528-5665', NULL, 'https://www.saltandwavessalon.com/',
   '3550 Lakeline Blvd #175',
   'Leander', 'TX',
   '78641',
   30.5449904, -97.86345299999999,
   '{"monday":{"open":"8AM","close":"9:30PM","isOpen":true},"tuesday":{"open":"8AM","close":"9:30PM","isOpen":true},"wednesday":{"open":"8AM","close":"9:30PM","isOpen":true},"thursday":{"open":"8AM","close":"9:30PM","isOpen":true},"friday":{"open":"8AM","close":"9:30PM","isOpen":true},"saturday":{"open":"8AM","close":"5PM","isOpen":true},"sunday":{"open":"","close":"","isOpen":false}}',
   4.5, 189,
   NULL,
   ARRAY['Hair salon'], '{}', ARRAY['beauty', 'Hair salons', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'salon-suites-spa', 'Salon Suites & Spa', 'Salon Suites & Spa is a hair business located in Leander. Hair salon, Bar PMU, Barber shop, Eyelash salon, Facial spa, Massage spa, Nail salon, Waxing hair removal service',
   'beauty', 'Hair salons',
   'https://lh3.googleusercontent.com/p/AF1QipOiUkn9J8FoXAYmgqjFvzupNyVlGA6O5NYtFy13=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/p/AF1QipOiUkn9J8FoXAYmgqjFvzupNyVlGA6O5NYtFy13=w800-h500-k-no'], '{}',
   '', NULL, 'https://www.txsalonsuites.com/',
   'Salon Suites & Spa 17 Personal Suites Inside, 2082 US-183 Suite 180',
   'Leander', 'TX',
   '78641',
   30.6272861, -97.86580099999999,
   '{"monday":{"open":"9AM","close":"7PM","isOpen":true},"tuesday":{"open":"9AM","close":"7PM","isOpen":true},"wednesday":{"open":"9AM","close":"7PM","isOpen":true},"thursday":{"open":"9AM","close":"7PM","isOpen":true},"friday":{"open":"9AM","close":"7PM","isOpen":true},"saturday":{"open":"9AM","close":"5PM","isOpen":true},"sunday":{"open":"","close":"","isOpen":false}}',
   4.7, 97,
   NULL,
   ARRAY['Hair salon, Bar PMU, Barber shop, Eyelash salon, Facial spa, Massage spa, Nail salon, Waxing hair removal service'], '{}', ARRAY['beauty', 'Hair salons', 'Leander'],
   'free', FALSE, FALSE),
  ('3714b0ea-56ae-426a-b2f1-5dff20efe29e', 'another-dimension-salon-leander', 'Another Dimension Salon Leander', 'Another Dimension Salon Leander is a hair business located in Leander. Hair salon, Beauty product supplier, Health spa, Spa',
   'beauty', 'Hair salons',
   'https://lh3.googleusercontent.com/gps-cs-s/AHVAwera-I_qNPy4b0bWReRzb7U2MKIpzSqQepppXhM64O1lKU9oppWKTF35fY4d3Mnx-52fCbcfuX0KHsU1qFrCEFo5cowv5jELahr1K1-RaJcwmrMdZ8lnwtfxAfvMODlFlPc_ySLurYd68ifl=w800-h500-k-no',
   ARRAY['https://lh3.googleusercontent.com/gps-cs-s/AHVAwera-I_qNPy4b0bWReRzb7U2MKIpzSqQepppXhM64O1lKU9oppWKTF35fY4d3Mnx-52fCbcfuX0KHsU1qFrCEFo5cowv5jELahr1K1-RaJcwmrMdZ8lnwtfxAfvMODlFlPc_ySLurYd68ifl=w800-h500-k-no'], '{}',
   '+1 512-762-1021', NULL, 'https://www.anotherdimensionsalon.com/',
   '2080 N US Hwy 183 #180',
   'Leander', 'TX',
   '78641',
   30.6273068, -97.865822,
   '{"monday":{"open":"10AM","close":"7PM","isOpen":true},"tuesday":{"open":"9AM","close":"7PM","isOpen":true},"wednesday":{"open":"9AM","close":"7PM","isOpen":true},"thursday":{"open":"9AM","close":"7PM","isOpen":true},"friday":{"open":"9AM","close":"7PM","isOpen":true},"saturday":{"open":"9AM","close":"5PM","isOpen":true},"sunday":{"open":"","close":"","isOpen":false}}',
   4.7, 51,
   NULL,
   ARRAY['Hair salon, Beauty product supplier, Health spa, Spa'], '{}', ARRAY['beauty', 'Hair salons', 'Leander'],
   'free', FALSE, FALSE)
;